//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turis.BusinessLayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Turis.BusinessLayer.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibilel&apos;applicazione perché possiede uno o più ruoli.
        /// </summary>
        public static string ApplicationInUse {
            get {
                return ResourceManager.GetString("ApplicationInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile ordinare i dati sulla colonna &apos;{0}&apos;.
        /// </summary>
        public static string OrderByError {
            get {
                return ResourceManager.GetString("OrderByError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante l&apos;ordinamento sulla colonna &apos;{OrderByColumn}&apos;.
        /// </summary>
        public static string OrderByLoggerError {
            get {
                return ResourceManager.GetString("OrderByLoggerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile eliminare il ruolo perché associato ad uno o più utenti e/o scope.
        /// </summary>
        public static string RoleInUse {
            get {
                return ResourceManager.GetString("RoleInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile eliminare lo scope group perché associato ad uno o più scope.
        /// </summary>
        public static string ScopeGroupInUse {
            get {
                return ResourceManager.GetString("ScopeGroupInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È stato impossibile inviare l&apos;e-mail a {0} per le seguenti cause: {1}.
        /// </summary>
        public static string SendEmailError {
            get {
                return ResourceManager.GetString("SendEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile eliminare il dato.
        /// </summary>
        public static string UnableToDelete {
            get {
                return ResourceManager.GetString("UnableToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore imprevisto durante l&apos;invio dell&apos;e-mail a {0}.
        /// </summary>
        public static string UnexpectedSendEmailError {
            get {
                return ResourceManager.GetString("UnexpectedSendEmailError", resourceCulture);
            }
        }
    }
}
