USE [master]
ALTER DATABASE [Turis] SET SINGLE_USER WITH ROLLBACK IMMEDIATE

RESTORE DATABASE [Turis] 
FROM  DISK = N'C:\Mario\Progetti\Turis\_bk\Turis_Dev.bak' WITH  FILE = 1,  
NOUNLOAD,  REPLACE,  STATS = 5

ALTER DATABASE [Turis] SET MULTI_USER

GO


